--<ScriptOptions statementTerminator=";"/>

ALTER TABLE BATCH_JOB_EXECUTION DROP CONSTRAINT JOB_INST_EXEC_FK;

ALTER TABLE BATCH_JOB_INSTANCE DROP CONSTRAINT SQL160914142940060;

ALTER TABLE BATCH_JOB_EXECUTION DROP CONSTRAINT SQL160914142941110;

DROP INDEX SQL160914142941110;

DROP INDEX SQL160914142941111;

DROP TABLE BATCH_JOB_EXECUTION_CONTEXT;

DROP TABLE BATCH_STEP_EXECUTION;

DROP TABLE BATCH_JOB_INSTANCE;

DROP TABLE BATCH_JOB_EXECUTION_SEQ;

DROP TABLE BATCH_JOB_EXECUTION_PARAMS;

DROP TABLE BATCH_JOB_EXECUTION;

DROP TABLE BATCH_STEP_EXECUTION_SEQ;

DROP TABLE BATCH_STEP_EXECUTION_CONTEXT;

DROP TABLE BATCH_JOB_SEQ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
	);

CREATE TABLE BATCH_STEP_EXECUTION (
	);

CREATE TABLE BATCH_JOB_INSTANCE (
		JOB_INSTANCE_ID BIGINT DEFAULT GENERATED_BY_DEFAULT NOT NULL,
		VERSION BIGINT,
		JOB_NAME VARCHAR(100) NOT NULL,
		JOB_KEY VARCHAR(32) NOT NULL
	);

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
	);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
	);

CREATE TABLE BATCH_JOB_EXECUTION (
		JOB_EXECUTION_ID BIGINT DEFAULT GENERATED_BY_DEFAULT NOT NULL,
		VERSION BIGINT,
		JOB_INSTANCE_ID BIGINT NOT NULL,
		CREATE_TIME TIMESTAMP NOT NULL,
		START_TIME TIMESTAMP DEFAULT NULL,
		END_TIME TIMESTAMP DEFAULT NULL,
		STATUS VARCHAR(10),
		EXIT_CODE VARCHAR(2500),
		EXIT_MESSAGE VARCHAR(2500),
		LAST_UPDATED TIMESTAMP,
		JOB_CONFIGURATION_LOCATION VARCHAR(2500) DEFAULT NULL
	);

CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
	);

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
	);

CREATE TABLE BATCH_JOB_SEQ (
	);

CREATE UNIQUE INDEX SQL160914142941110 ON BATCH_JOB_EXECUTION (JOB_EXECUTION_ID ASC);

CREATE INDEX SQL160914142941111 ON BATCH_JOB_EXECUTION (JOB_INSTANCE_ID ASC);

ALTER TABLE BATCH_JOB_INSTANCE ADD CONSTRAINT SQL160914142940060 PRIMARY KEY (JOB_INSTANCE_ID);

ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT SQL160914142941110 PRIMARY KEY (JOB_EXECUTION_ID);

ALTER TABLE BATCH_JOB_EXECUTION ADD CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
	REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID);

