SELECT MAX(CAST(STRING_VAL AS INTEGER)) 
  FROM %PREFIX%JOB_EXECUTION_PARAMS JP, %PREFIX%JOB_EXECUTION JE, %PREFIX%JOB_INSTANCE JI
 WHERE JP.JOB_EXECUTION_ID = JE.JOB_EXECUTION_ID
   AND JI.JOB_INSTANCE_ID = JE.JOB_INSTANCE_ID
   AND JP.KEY_NAME='processo' 
   AND JI.JOB_NAME=? 